import { Amplify } from "aws-amplify";
import outputs from "@/amplify_outputs.json";

/**
 * Single place where Amplify is configured.
 *
 * `amplify_outputs.json` is generated by ampx and untracked; when it is absent,
 * scripts/ensure-amplify-outputs.mjs writes a stub carrying `_stub: true` so the
 * bundle still resolves. Configuring Amplify against that stub would fail at
 * runtime with an unhelpful error, so we skip it and report the state instead.
 */
const isStub = (outputs as { _stub?: boolean })._stub === true;

/** True when Amplify has real backend outputs and auth can actually be used. */
export const amplifyConfigured = !isStub;

if (amplifyConfigured) {
  // Safe to call more than once.
  Amplify.configure(outputs);
}
